### PR TITLE
Add check for abortRequested

### PR DESCRIPTION
**Pull request by dagwieers**
This was requested by Kodi devs.

### CODE REVIEW

**Comment by im85288** [comment]
Sorry I already committed my changes! They also wanted the sleep out, it'll make things easier just to give them what they want rather than risk another round of tag/untag etc just for something we only use for testing creating skins

**Comment by im85288** [comment]
How about this from @anxdpanic:

```
monitor = Monitor()
while popup and step < timeout and not monitor.abortRequested():
	if popup.pause:
		continue
	if monitor.waitForAbort(wait):
		break
	popup.update_progress_control(timeout, wait)
	step += wait
```

**Comment by dagwieers** [comment]
It is always better to use PRs and use a review process. At least the PR gets sanity and unit tested (unit tests up to 42%)

**Comment by dagwieers** [comment]
Again, I don't think it makes sense to make it more complicated than it has to be. Using sleep is fine for values of 100ms, and I expect the overhead to be bigger when using `waitForAbort()`. There is no need to abort faster than 100ms. If that would be the case, we have other code paths where we are using sleep() now.

**Comment by im85288** [comment]
Ok cool let's go for this and see what they say.

**Comment by dagwieers** [comment]
I rebased my PR.

**Comment by dagwieers** [comment]
We probably want to test this for a few hours before putting this up again.

**Comment by im85288** [comment]
Too late :) I submitted them for a review. Let's see what happens and test in the meantime. Strangely enough for Leia the Travis build worked and for Matrix it failed!

**Comment by dagwieers** [comment]
The downloads are loadbalanced and apparently downloads.kodi.tv has an expired SSL certificate :-/

**Comment by im85288** [comment]
Oops! Someone needs to do some configuration magic.

**Comment by dagwieers** [comment]
I actually implemented HTTP retries to recover from issues like this: https://github.com/xbmc/addon-check/pull/217
So I don't understand why this did not help here. I can see it retried 5 times, but probably the same host.

urllib3 should support round-robin DNS entries though.

**Comment by im85288** [comment]
The submit was approved this time. In matrix repo in a couple of hours apparently. Cool

**Comment by im85288** [comment]
Also for future after a review we should Only need to remove the tag then retag.
Closing the PR is not needed:


git tag -d <tag_name>

git push --delete origin tagname

git tag tagname && git push --tags

**Comment by dagwieers** [comment]
Now let's hope we did not break it :wink:

**Comment by im85288** [comment]
Fingers crossed!

**Comment by dagwieers** [comment]
I tried the v1.1.1 release and I do not see a pop-up appearing :disappointed:

**Comment by im85288** [comment]
Oops, it must be that waitForAbort thing in player. Probably should have tested it first!

**Comment by dagwieers** [comment]
I changed it back to a sleep and things work correctly again. But I do not understand what is going on.

**Comment by im85288** [comment]
I wonder if it needs to be conditional instead? Looking at the implementation it seems it returns no matter what so yes very strange

**Comment by dagwieers** [comment]
Ok, so waitForAbort() is in seconds, where sleep() is in ms :roll_eyes:

**Comment by dagwieers** [comment]
I guess we need v1.1.2 now...

**Comment by im85288** [comment]
Whoops! Yes I guess we do 😊

**Comment by im85288** [comment]
Corrected this now, will push out v1.1.2

**Pull request merged**
