### PR TITLE
Assorted fixes

### PR DESCRIPTION
**Pull request by dagwieers**
This PR includes:
- Various small fixes to tests
- The use of the Addon Signals master branch for testing

This fixes tests as seen at: https://travis-ci.org/dagwieers/service.upnext/branches

### CODE REVIEW

**Comment by dagwieers** [comment]
@im85288 Can you please look into why Travis is no longer working? Tests were failing and we did not know because there's no checks being made automatically.

**Comment by im85288** [comment]
@dagwieers The build started to fail from the merge of issue #93 

It looks like the problem is only there for python 3.5 where I see the following exception:

`Traceback (most recent call last):
  File "/home/travis/build/im85288/service.upnext/test/test_encoding.py", line 71, in test_to_addon_signals
    decoded_data = AddonSignals._decodeData('["%s"]' % encoded_data)  # pylint: disable=protected-access
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/AddonSignals.py", line 21, in _decodeData
    return json.loads(base64.b64decode(data[0]))
  File "/opt/python/3.5.6/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'`

**Comment by dagwieers** [comment]
This is related to a bug we fixed in AddonSignals. The master branch should have this fixed. The real build issues happened later.

**Comment by dagwieers** [comment]
@im85288 I would like to see the Travis integration fixed in GitHub. I don't know when this stopped working...

**Comment by im85288** [comment]
@dagwieers can you view this: https://travis-ci.org/im85288/service.upnext/builds ?

**Comment by im85288** [comment]
@dagwieers travis build passing now thanks, I have added you as a Collaborator so you should be able to see everything I can

**Comment by dagwieers** [comment]
@im85288 Thanks, but I can't seem to look into why Travis is not integrated in GitHub for this project. It worked for some time though, see the check-marks on this page:
https://github.com/im85288/service.upnext/pulls?page=2&q=is:pr+is:closed

**Comment by im85288** [comment]
@dagwieers I did get a notification email that the travis build succeeded when I merged this pull request and the home code page badge now shows it as passed. Is this what you mean?

**Comment by dagwieers** [comment]
So the integration of GitHub and Travis I am looking for is:
- Pull requests get a green markin the PR overview to indicate all tests ran successfully
  https://github.com/im85288/service.upnext/pulls?page=3&q=is:pr+is:closed
- Each pull request shows a **All checks have passed** section at the end of the PR (includes Travis and Codecov)
  https://github.com/im85288/service.upnext/pull/72

This used to work fine up until November 7.

**Comment by dagwieers** [comment]
It seems to be working again, I rebuild some of the older PRs and they get marked !

**Pull request merged**
