### PR TITLE
Add project badges

### PR DESCRIPTION
**Pull request by dagwieers**
This is a set of project badges we have been using in other projects as
well. Feel free to add or remove as you please.

It does require Travis-CI testing and Codecov coverage, which I hope we
can add soon.

### CODE REVIEW

**Comment by dagwieers** [comment]
Feel free to keep this until we have Travis-CI and Codecov integrated properly.

**Comment by dagwieers** [comment]
You can have a preview at:
https://github.com/im85288/service.upnext/blob/12ad78b040de531b4b724bab7153c39a1df2dfcc/README.md

**Comment by im85288** [comment]
Super cool! Thanks

**Comment by dagwieers** [comment]
BTW Have you seen this: http://mirrors.kodi.tv/stats?downloadstats&filter=service.upnext

It would be nice to have those stats in a badge too ;-)

**Comment by im85288** [comment]
Wow that’s a lot of downloads! No I hadn’t seen it before. Agree that would be a cool stat to add if we can

**Pull request merged**
