### PR TITLE
Prepare for v1.1.0 release

### PR DESCRIPTION
**Pull request by dagwieers**
Update README and addon.xml for release.

### CODE REVIEW

**Comment by dagwieers** [comment]
Here is an overview of everything related to an upcoming v1.1.0 release: https://github.com/im85288/service.upnext/milestone/9?closed=1

**Comment by dagwieers** [comment]
So the question is what do we do with:
- Open bug reports (#134, #135, #139)
- Open feature pull requests (#133)
- Missing translations (see `make language` output)

**Comment by dagwieers** [comment]
Rationale for choosing v1.1.0 as the next version. Given version X.Y.Z:
- X would be used for important new releases (rewrite, breaking changes)
- Y would be used for new functionality or changes
- Z would be used for bugfix-only releases

**Comment by im85288** [comment]
> Rationale for choosing v1.1.0 as the next version. Given version X.Y.Z:
> 
> * X would be used for important new releases (rewrite, breaking changes)
> * Y would be used for new functionality or changes
> * Z would be used for bugfix-only releases

Sounds good to me, with regards the open bug reports I guess we can have to leave them for the next release (if indeed we can resolve them). Same for the PR? 

The Kodi guys normally complain if I make too frequent releases but it has been a fair bit of time between this and the previous version so all should be fine,

**Comment by dagwieers** [comment]
I will (finally) call out to existing translators (#112) to fix the remaining issues. In the meantime we can test the current master branch and ask our consumers to perform tests as well?
And maybe release by Wednesday or Thursday?

**Comment by im85288** [comment]
Yes fine with me for mid week release

**Comment by dagwieers** [comment]
Call out for testing the master branch to all stakeholders: @angelblue05 @sualfred @mediaminister @arvvoid @anxdpanic @CastagnaIT @Dis90 @faush01 @jellyfin @croneter @thebertster @ShaVerZ @venom123 @angus2064 @stathis95194 

You can download the ZIP file from: https://github.com/im85288/service.upnext/archive/master.zip
And install it from **Settings » Add-ons » Install from zip file**

**Comment by CastagnaIT** [comment]
i did a couple of tests on Kodi 19 with play_url and seem works good

**Comment by thebertster** [comment]
> 
> 
> Call out to all stakeholders for testing the master branch: @angelblue05 @sualfred @mediaminister @arvvoid @anxdpanic @CastagnaIT @Dis90 @faush01 @jellyfin @croneter @thebertster @ShaVerZ @venom123 @angus2064 @stathis95194
> 
> You can download the ZIP file from: https://github.com/im85288/service.upnext/archive/master.zip
> And install it from **Settings » Add-ons » Install from zip file**

Working OK for me in LibreElec 9.2.0 (other than obviously having to do the 1 second adjustment workaround for #139).

**Comment by dagwieers** [comment]
@thebertster I hope we can focus on issue #139 after upcoming release (as part of restructuring the code). If this was more wildly reported that would no doubt also make a difference on how we would handle this.

**Comment by anxdpanic** [comment]
All seems good for me as well, tested on Windows and it's now in use on my main OSMC (nightly) installation.

**Comment by dagwieers** [comment]
@im85288 I wonder if for new installations we should enable the runtime-based notification_time settings instead of the default 30 seconds. Not sure what others think about this?

**Comment by im85288** [comment]
@dagwieers - Yes that's fine for me, let's see what others think about this. If no objections let's go for it.

**Comment by dagwieers** [comment]
Ready to be merged. Please merge #165 first.
Then this is ready to be tagged as `v1.1.0` and released.

**Comment by im85288** [comment]
release candidate created here: https://github.com/im85288/service.upnext/releases/tag/1.1.0

**Comment by dagwieers** [comment]
I added the changelog and a ZIP file to the release. While the branch ZIP file works as well, the provided ZIP file is more minimalistic and closer to what will become available from the Kodi repository.

**Comment by dagwieers** [comment]
@im85288 Can we also push it to the Kodi repository? I can make the PR, but since I am not listed as "provider", you will have to sign off on it. So maybe it is easier if you do it yourself.

As soon as it hits the Kodi repository, the Netflix add-on can start making the modifications to the master branch to make `play_url` and the new `notification_offset` work.

**Comment by im85288** [comment]
@dagwieers Sure no problem I will make the PR tonight once back from work.

**Comment by im85288** [comment]
@dagwieers PR made to the Kodi Repository: https://github.com/xbmc/repo-scripts/pull/1276

**Comment by im85288** [comment]
@dagwieers - PR merged: https://github.com/xbmc/repo-scripts/pull/1276#event-2960747397 

Nice work :)

**Pull request merged**
