### PR TITLE
Add spanish translation

### PR DESCRIPTION
**Pull request by dagwieers**
This is the PR from https://github.com/sagatxxx/service.upnext/pull/1

### CODE REVIEW

**Comment by dagwieers** [comment]
I noticed the location is wrong. It should have been in **resource.language.es_es** not **resource.language.es**.

**Comment by dagwieers** [comment]
I do not have the proper privileges to make a change in your branch. :disappointed:

**Comment by im85288** [comment]
That's annoying, I thought as a collaborator you would have all the same privileges. For now I have just committed it directly to the master branch so will close this PR. 

Thanks guys

**Comment by dagwieers** [comment]
I wonder how this could have gone wrong, as I clearly provided the right instructions:
https://github.com/im85288/service.upnext/issues/112#issuecomment-574305059

**Comment by im85288** [comment]
Easy mistake I guess, never mind it’s sorted now :)

**Comment by dagwieers** [comment]
It's not sorted unless I make the PR myself, which defeats the purpose :-/

**Pull request closed without merging**
