### PR TITLE
Fix all pylint issues

### PR DESCRIPTION
**Pull request by dagwieers**
This implements fixes for all reported flake8 issues.

Beware of two things that require more testing:
- pylint complains about that Control does not have setPercent ?

### CODE REVIEW

**Comment by dagwieers** [comment]
So I already prepared this, but I now have to resolve the remaining conflicts ;-)

**Comment by im85288** [comment]
Cool, I’ll check back later or maybe tomorrow as it’s movie time! Cheers

**Comment by dagwieers** [comment]
There is one more thing to do after this:
- Add integration and unit tests

And more importantly, unicode-related tests, because that is going to tell if it works fine for both Python 2 and Python 3. And then it would be nice if we could start the service, and signal things to test all code-paths.

We could then also add coverage support, to see if we are testing all codepaths properly. For this project a near 100% coverage is possible.

**Comment by im85288** [comment]
Excellent, really appreciate the improvements and fully agree if we have tests we can be more confident of any further changes that we have not broken any of the current functionality

**Pull request merged**
