### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by dagwieers**
This PR adds:
- More flake8 and pylint fixes (got lost during conflict resolution)
- Include Kodi stubs
- Integration tests for testing all codepaths *-- Unfinished*
- Unit tests (for unicode and python2/3) *-- TODO*
- Code coverage testing

### CODE REVIEW

**Comment by dagwieers** [comment]
This will be a work in progress...

**Comment by im85288** [comment]
Nice, your very fast!

**Comment by dagwieers** [comment]
Just reusing what we have done now for 4 other projects.
So it is mostly copy&pasting the right bits.

The unit/integration tests will be a lot slower ;-)

**Comment by dagwieers** [comment]
So it appears I know too little about Up Next to continue.
I start the service with the existing stub libraries.
But then we need to add scripts that call the service to perform actions.
And we need unit-tests to test functionality in isolation that we cannot test using integration tests.

And next to the above, we want to modify the existing xbmc/xbmcgui functionality as if it acts as normal Kodi. So the Player needs to act as if it is playing a file that runs until the end, and the WindowXMLDialog() needs to output something so we know what is on-screen, etc.

**Comment by dagwieers** [comment]
I get this error when I disable the plugin. I don't think my changes have anything to do with it though.
```
2019-10-19 04:12:36.319 T:1533842288   ERROR: EXCEPTION: Unknown addon id 'service.upnext'.
2019-10-19 04:12:36.326 T:1533842288   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Unknown addon id 'service.upnext'.
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/service.upnext/service.py", line 8, in <module>
                                                Monitor().run()
                                              File "/storage/.kodi/addons/service.upnext/resources/lib/monitor.py", line 55, in run
                                                self.log("======== STOP service.upnext ========", 0)
                                              File "/storage/.kodi/addons/service.upnext/resources/lib/monitor.py", line 22, in log
                                                utils.log("[%s] %s" % (utils.addon_id(), class_name), str(msg), int(lvl))
                                              File "/storage/.kodi/addons/service.upnext/resources/lib/utils.py", line 23, in addon_id
                                                return to_unicode(xbmcaddon.Addon().getAddonInfo('id'))
                                            RuntimeError: Unknown addon id 'service.upnext'.
                                            -->End of Python script error report<--
```

**Comment by dagwieers** [comment]
So the current code seems to work on LibreELEC v9.0.2 using Leia just fine as before.
It still needs proper testing on Python 3 and using Unicode input.

**Comment by dagwieers** [comment]
cc @mediaminister As you have the most experience with Unicode issues, we just moved this code to using unicode_literals for Python 2.7, so you probably know what the usual suspects are?

**Comment by mediaminister** [comment]
urllib and all xbmc... libraries don't like unicode in Python 2.7, so decoding input and encoding output is needed.
I can't remember unicode problems with other libraries right now.

**Comment by im85288** [comment]
> I get this error when I disable the plugin. I don't think my changes have anything to do with it though.
> 
> ```
> 2019-10-19 04:12:36.319 T:1533842288   ERROR: EXCEPTION: Unknown addon id 'service.upnext'.
> 2019-10-19 04:12:36.326 T:1533842288   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.RuntimeError'>
>                                             Error Contents: Unknown addon id 'service.upnext'.
>                                             Traceback (most recent call last):
>                                               File "/storage/.kodi/addons/service.upnext/service.py", line 8, in <module>
>                                                 Monitor().run()
>                                               File "/storage/.kodi/addons/service.upnext/resources/lib/monitor.py", line 55, in run
>                                                 self.log("======== STOP service.upnext ========", 0)
>                                               File "/storage/.kodi/addons/service.upnext/resources/lib/monitor.py", line 22, in log
>                                                 utils.log("[%s] %s" % (utils.addon_id(), class_name), str(msg), int(lvl))
>                                               File "/storage/.kodi/addons/service.upnext/resources/lib/utils.py", line 23, in addon_id
>                                                 return to_unicode(xbmcaddon.Addon().getAddonInfo('id'))
>                                             RuntimeError: Unknown addon id 'service.upnext'.
>                                             -->End of Python script error report<--
> ```
> 
> It seems as soon as it is disabled, this call fails service.py, rather than stopping it.
> 
> **Update:** I can confirm it happens both on v1.0.1 and v1.0.2 too.

Yes that’s something I need to fix eventually, it did not seem to effect anything really so I had forgotten about it

**Comment by dagwieers** [comment]
The fix is easy, I'll fix it.

**Comment by im85288** [comment]
Great thanks, merging this in now

**Comment by dagwieers** [comment]
@mediaminister Thanks !

The biggest issue here is that our xbmc stubs do not mimic the actual xbmc libraries wrt. unicode. So we can't do proper unicode testing for everything related to the xbmc libraries.

**Comment by dagwieers** [comment]
@im85288 I removed the `unicode_to_ascii()` function. I wanted to discuss why it was used. Is the problem that Kodi's font doesn't implement these listed unicode-characters, or is there some other issue?

**Comment by im85288** [comment]
@dagwieers it was something carried over from my previous addon (next up) but to be honest I do not know if it is really needed

**Comment by dagwieers** [comment]
@im85288 Can you enable travis-ci ?

**Comment by im85288** [comment]
@dagwieers sure no problem, that should be done now. If I have missed something please let me know

**Comment by mediaminister** [comment]
> The biggest issue here is that our xbmc stubs do not mimic the actual xbmc libraries wrt. unicode. So we can't do proper unicode testing for everything related to the xbmc libraries.

Right, unicode handling is just one of the parts we don't properly mimic. Taking into account that we like to support Kodi 17, Kodi 18 and Kodi 19, I'm not sure if trying to fix this is worth the effort.

**Pull request merged**
