### PR TITLE
Fix to prevent unwanted playback when using playlist queueing method

### PR DESCRIPTION
**Pull request by MoojMidge**
This is an interim fix to the unwanted playback problem, originally identified by @thebertster in #204 and also subsequently by others in #227.

Note that this wont fix all the issues that were identified in the discussion associated with #204, but should address the most common problem for most installations.

### CODE REVIEW

**Review by im85288 — APPROVED** [review]

**Comment by im85288** [comment]
@MoojMidge looks good to me thanks for fixing these issues. I'll await @dagwieers review before merging.

**Comment by MoojMidge** [comment]
No problem.

The only thing to bear in mind with this PR is that the timing issues identified in #204 may now become more apparent now that the playback not working and unwanted playback issues have been worked around.

However, the timing issues probably wont impact as many people as the other problems (I could never directly reproduce the timing issues), and it is a bit too complicated to fix simply/quickly, so on balance, it is probably safe to leave it to later.

**Comment by Razzeee** [comment]
Seems to stop okay now. But it also changed how the `Close` button works, is that expected? It now does, what I would expect from the `Stop` button.

**Comment by MoojMidge** [comment]
Expected? Yes - see https://github.com/im85288/service.upnext/pull/237/files#diff-437f4c1ae1704e3a5689fd1af3f8586471488ab7458c51afc1a157224e33dddcR110-R115

Ideal? No, but this PR was not meant to be a full fix for all the issues that were discovered.

The original code has a couple of issues related to the stop and close buttons and the stopAfterClose setting:
- there is no way to distinguish whether a user pressed the back key, clicked the cancel button, or clicked the stop button. All three actions set the same cancel status variable.
- the Still Watching? dialog does not actually use the stopAfterClose setting, and will never show a stop button.

What should happen (in my opinion) is that:
- pressing the back key should ignore the stopAfterClose setting and only close the open dialog.
- the stopAfterClose setting should function in the Still Watching? dialog and show a stop button rather than a close button, if enabled.
- there should be a separate stop status variable that identifies whether the user clicked the stop button so that immediately stopping playback should only occur when requested by the user.
- if the user does nothing and the default action is set to stop, then playback should also stop immediately.

Didn't want to make more than the bare minimum changes to resolve the original problem, but can put together a bit of a compromise solution.

**Comment by dagwieers** [comment]
I haven't tested this myself, so I am not sure I am the right person to approve this.
But it seems to fix most people's problems so by popular demand...

**Pull request merged**
