### PR TITLE
Translation fixes

### PR DESCRIPTION
**Pull request by dagwieers**
This PR includes:
- A fix for the translation tests in Makefile
- A fix for the German .po file as reported by msgcmp
- Make all translations consistent

### CODE REVIEW

**Comment by dagwieers** [comment]
Hmm, Travis stopped working?

**Comment by dagwieers** [comment]
Why were these fixes not merged for the v10.4 release? ;-)

**Comment by im85288** [comment]
Whoops missed it, sorry about that. Merging now

**Comment by dagwieers** [comment]
No worries ;-)
Should we reach out to past translators to get more translation fixes in?

**Comment by im85288** [comment]
Sounds like a plan, I promised to show you the Transifex solution (I have been a bit lazy!) as that is the correct way to manage the languages. I will add you as a maintainer if you either create an account and give me your user name or let me know an email address to add you with?

**Comment by im85288** [comment]
https://www.transifex.com/emby/teams/92605

**Comment by dagwieers** [comment]
@im85288 How do you get your add-on added to one of the Transifex projects?
I found your add-on here:
- https://www.transifex.com/emby/up-next/

I would be most interested to see it added to one of these instead:
- https://www.transifex.com/teamxbmc/kodi-addons/
- https://www.transifex.com/teamxbmc/xbmc-addons/dashboard/

**Comment by im85288** [comment]
@dagwieers - I think I just created my own Team and added the addon. I may move it to a new location as I do not use Emby anymore but it’s not a priority. As mentioned in the other comments I can add you as a team member so that you can add translations etc as needed

**Pull request merged**
