### PR TITLE
Updated german translation for v1.1.0

### PR DESCRIPTION
**Pull request by tweimer**
See #112

### CODE REVIEW

**Comment by dagwieers** [comment]
#118 will again change the translations, so it is better to wait until everything has settled and we call for translations before an upcoming release.

**Comment by im85288** [comment]
Merging anyway, new additions can come in a different PR

**Comment by tweimer** [comment]
@im85288 I resolved the conflicts. Ready to merge now.

**Comment by im85288** [comment]
@tweimer Great thanks 😊

**Pull request merged**
