### PR TITLE
Update Italian translation

### PR DESCRIPTION
**Pull request by EffeF**

### CODE REVIEW

**Comment by dagwieers** [comment]
I think it is better to wait until we are ready to release, because we are still adding/modifying functionality that influences translations.

**Comment by im85288** [comment]
Good point not sure I can un merge but for future ones will keep them open until things are settled

**Comment by dagwieers** [comment]
I think it is best we ask translators to update translations.
And do this a few days before we expect a release.

I was planning to do this and call out to a lot of new translators as well, but I waited until #100 because of the impact. And now with #118 there's again more impact.

**Comment by im85288** [comment]
Fair enough, there’s also now been two reports of the Popup not showing so something we need to get to the bottom off

**Comment by dagwieers** [comment]
Two ? I only know of one: #117 
Maybe because I think #86 is related to enabling a broken Developer mode.

**Comment by im85288** [comment]
Someone posted in issue 18 (sorry cannot link) which is already closed so I asked them to create a new issue which they have not. Not much info though

**Comment by dagwieers** [comment]
BTW You can simply type: &lt;hash&gt; &lt;issue number&gt; and it automatically creates a link. Like this: #18 

The Venom/Seren issue (#91) was reported even before we released v1.0.7. And they tested combinations of old/new Addon Signals and older/newer UpNext. So something else is going on there and I suspect a logic issue in the code. When I reviewed Venom's code I saw some practices that could potentially lead to issues unrelated to UpNext.

**Pull request merged**
