### PR TITLE
Fix SonarCloud integration

### PR DESCRIPTION
**Pull request by MoojMidge**
@im85288 - I noticed that a number of the existing workflows were failing. Have fixed most of them up, but the SonarCloud integration looks like it will need a new user authorisation token to be created.

You will need to go to https://sonarcloud.io/account/security to (re)create the user token.

Then go to https://github.com/im85288/service.upnext/settings/secrets/actions and create a new repository secret named `SONAR_TOKEN` with the secret set to the newly created user token.

### CODE REVIEW

**Comment by im85288** [comment]
@MoojMidge great stuff and thanks for the detail on fixing the sonar cloud. I will have a look in the next couple of days to fix it, but please ping me if it's not done by next week in case I got distracted.

**Comment by MoojMidge** [comment]
@im85288 - bump

**Comment by im85288** [comment]
@MoojMidge there was already a token in sonarcloud linked, but to be safe I created a new one and updated the value in the secrets section. 

image

Hopefully it's all good now

**Comment by MoojMidge** [comment]
Not sure why it wasn't authenticating before, but that part is now OK.

The analysis execution still fails though - will try and enable logging to figure out why, sometime down the track.

**Comment by MoojMidge** [comment]
Re-ran one of the old CI actions and it failed with an error indicating that automatic analysis was enabled, so the CI action may no longer be necessary. Can be removed if it causes a problem, but the (automatic?) analysis worked anyway.

**Pull request merged**
