### PR TITLE
Replace Developer mode with testing a specific window

### LINKED ISSUE #86: Clicking Play Next or Close does nothing
I cannot manage to make this work. All settings to Up Next and Seren or Venom are enabled and identical. Popup comes up as expected on the time expected, but even if click Play Next, nothing happens. Stream finishes and continues to the next one only when time runs out.

Log isn't very helpful as it shows that everything is fine even though it isn't. Am i missing something?

A thing i noticed is that at the beginning of each episode, Up Next shows the popup for a completely unrelated show (Game of Thrones s2e4) which i need to "Close" 3 times to disappear. I found nothing on log regarding this though

`2019-11-17 19:50:08.468 T:14427  NOTICE: Opening stream: 0 source: 1024
2019-11-17 19:50:41.590 T:12617  NOTICE: UP NEXT Monitor -> log : Calling autoplayback totaltime - playtime is 49.5129394531
2019-11-17 19:50:41.603 T:12617  NOTICE: UP NEXT Api -> log : handle_addon_lookup_of_next_episode episode returning data {"rating": 8.0, "tvshowid": "tt4524056", "art": {"tvshow.fanart": "https://www.thetvdb.com/banners/fanart/original/294741-8.jpg", "thumb": "https://www.thetvdb.com/banners/episodes/294741/5202823.jpg", "tvshow.clearart": "", "tvshow.landscape": "https://www.thetvdb.com/banners/fanart/original/294741-8.jpg", "tvshow.poster": "https://www.thetvdb.com/banners/posters/294741-15.jpg", "tvshow.clearlogo": ""}, "plot": "Macarena's confrontation with self-appointed prison queen bee Zulema endangers her family.", "season": 1, "title": "Episode 3", "episodeid": 1848870, "firstaired": "2015-05-04", "episode": 3, "playcount": 0, "showtitle": "Vis a Vis"}
2019-11-17 19:50:41.614 T:12617  NOTICE: UP NEXT Api -> log : handle_addon_lookup_of_current episode returning data {"rating": 0.0, "tvshowid": "tt4524056", "art": {"tvshow.fanart": "https://www.thetvdb.com/banners/fanart/original/294741-8.jpg", "thumb": "https://www.thetvdb.com/banners/episodes/294741/5202822.jpg", "tvshow.clearart": "", "tvshow.landscape": "https://www.thetvdb.com/banners/fanart/original/294741-8.jpg", "tvshow.poster": "https://www.thetvdb.com/banners/posters/294741-15.jpg", "tvshow.clearlogo": ""}, "plot": "Macarena is caught with a package of drugs and is tricked into revealing who owned them.", "season": 1, "title": "Episode 2", "episodeid": 1848869, "firstaired": "2015-04-27", "episode": 2, "playcount": 1, "showtitle": "Vis a Vis"}
2019-11-17 19:50:41.624 T:12617  NOTICE: UP NEXT PlaybackManager -> log : episode details {"rating": 8.0, "tvshowid": "tt4524056", "art": {"tvshow.fanart": "https://www.thetvdb.com/banners/fanart/original/294741-8.jpg", "thumb": "https://www.thetvdb.com/banners/episodes/294741/5202823.jpg", "tvshow.clearart": "", "tvshow.landscape": "https://www.thetvdb.com/banners/fanart/original/294741-8.jpg", "tvshow.poster": "https://www.thetvdb.com/banners/posters/294741-15.jpg", "tvshow.clearlogo": ""}, "plot": "Macarena's confrontation with self-appointed prison queen bee Zulema endangers her family.", "season": 1, "title": "Episode 3", "episodeid": 1848870, "firstaired": "2015-05-04", "episode": 3, "playcount": 0, "showtitle": "Vis a Vis"}
2019-11-17 19:50:41.650 T:12617  NOTICE: UP NEXT PlaybackManager -> log : played in a row settings "3"
2019-11-17 19:50:41.660 T:12617  NOTICE: UP NEXT PlaybackManager -> log : played in a row 1
2019-11-17 19:50:41.669 T:12617  NOTICE: UP NEXT PlaybackManager -> log : showing next up page as played in a row is 1
2019-11-17 19:50:48.903 T:12617  NOTICE: UP NEXT PlaybackManager -> log : playing media episode
2019-11-17 19:50:48.913 T:12617  NOTICE: UP NEXT Api -> log : sending data to addon to play:  {"item_id": 1848869}
2019-11-17 19:50:48.921 T:12617  NOTICE: UP NEXT Monitor -> log : Up Next style autoplay succeeded.`

### PR DESCRIPTION
**Pull request by dagwieers**
Since Developer mode requires playing a file and this may confuse users
accidentally enabling developer mode, it may be easier if we simply show
the selected window (pop-up) from the settings directly.

This PR includes:
- Removing Developer mode in favor of testing popup windows
- Move script and service entry points into resources/lib/
- Add script.py

This fixes #86 and #120

### CODE REVIEW

**Comment by dagwieers** [comment]
@im85288 @notoco Try this out. It doesn't have details yet, and no progress, but those are just small things now.

**Comment by notoco** [comment]
I will test it tomorow :)

**Comment by dagwieers** [comment]
So I think this is ready to be tested. There is one important change to how this works for skinners as well. For testing we cannot "fake" `$INFO[Player.TimeRemaining(ss),,]`, but for most other information we use the window properties.

So my solution was to add the remaining time to the window properties and use that in our skins. This means that if people use `$INFO[Player.TimeRemaining(ss),,]` themselves it will work, but not when testing.

That said if people use the translations, like they should, this is not a real problem.

**Comment by dagwieers** [comment]
Have people tested this?

**Comment by im85288** [comment]
Not yet will try and do so and give some feedback

**Comment by notoco** [comment]
I didn't have time, maybe tomorrow I will succeed.

**Comment by dagwieers** [comment]
And there I was refreshing my browser all day waiting for that glimpse of approval 🙃

**Comment by notoco** [comment]
It works perfectly - it is a much faster solution than the previous one. It's awesome. I can see how much I need to improve in my skin modification :) Perfect.

**Comment by im85288** [comment]
@dagwieers Works perfectly, great stuff!

**Pull request merged**
