### PR TITLE
Add a program entry in the addon section

### PR DESCRIPTION
**Pull request by dagwieers**
This adds an entry in the add-on section for Up Next.

### CODE REVIEW

**Comment by im85288** [comment]
Cool, I’ve not been feeling great but will get round to doing a release this week sometime

**Comment by dagwieers** [comment]
Not sure if we want to do this, we do this for InputStream Helper, but the use-case is different.

**Comment by im85288** [comment]
If it makes finding the addon easier for end users that’s a positive

**Comment by dagwieers** [comment]
Please release v1.0.6, keep these improvements for the next version.

**Comment by dagwieers** [comment]
> If it makes finding the addon easier for end users that’s a positive

I agree.

**Comment by im85288** [comment]
Will do thanks

**Pull request merged**
