### PR TITLE
WIP: Assorted set of fixes

### PR DESCRIPTION
**Pull request by dagwieers**
This PR includes:
- Fix for stopping service.py gracefully
- Simplify utils.log() interface
- Dutch translation fix
- Redesign JSONRPC (ought to become a function, imo)
- Add documentation to utils.py
- Two unicode improvements

### CODE REVIEW

**Comment by dagwieers** [comment]
No! This was a Work in progress (as in: Untested).
You like to live on the edge ;-)

**Comment by im85288** [comment]
Haha yes, plenty time to test before the next release :)

**Comment by dagwieers** [comment]
The checks also were not green (because of an invalid-name issue that I was fixing).
Maybe it is best you configure your project to not allow for merging PRs if the checks fail?

**Comment by im85288** [comment]
I wasn’t aware I could do that, will configure it later today or tomorrow

**Pull request merged**
