### PR TITLE
Implement new settings

### PR DESCRIPTION
**Pull request by dagwieers**
This implements reorganized settings:
- 3 sections: Interface, Behaviour, Expert
- Customize the notification time by episode length
- Various improvements to translation strings

The changes are in the second commit (adf6dd08bee69937c34948cdc5d2b95604d60c7f), the first commit is PR #114.

The new settings look like this:
screenshot031
screenshot036
screenshot037
screenshot038

### CODE REVIEW

**Comment by dagwieers** [comment]
This is still a draft until everyone approves.

**Comment by dagwieers** [comment]
The current PR still has the logic for **shortPlayMode**, **shortPlayLength** and **shortPlayNotification** included. I will remove it if it is decided that we no longer need this.

**Comment by dagwieers** [comment]
So I think this is ready to be tested and reviewed.

**Comment by dagwieers** [comment]
> Please remove the comment with VRT NU addon for the addon id and path

Fixed. And I removed it from the original VRT NU code as well, as we reuse this elsewhere too.

**Comment by anxdpanic** [comment]
Disabling the service using this PR causes the RunTime exception below;

```
2019-11-28 20:53:39.622 T:5868   DEBUG: CServiceAddonManager: stopping service.upnext.
2019-11-28 20:53:39.622 T:18000   ERROR: EXCEPTION: Unknown addon id 'service.upnext'.
2019-11-28 20:53:39.623 T:18000   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'RuntimeError'>
                                            Error Contents: Unknown addon id 'service.upnext'.
                                            Traceback (most recent call last):
                                              File "C:\Programs\Kodi 19\portable_data\addons\service.upnext\service.py", line 8, in <module>
                                                UpNextMonitor().run()
                                              File "C:\Programs\Kodi 19\portable_data\addons\service.upnext\resources\lib\monitor.py", line 72, in run
                                                self.log('Service stopped', 0)
                                              File "C:\Programs\Kodi 19\portable_data\addons\service.upnext\resources\lib\monitor.py", line 25, in log
                                                utils.log(msg, name=self.__class__.__name__, level=level)
                                              File "C:\Programs\Kodi 19\portable_data\addons\service.upnext\resources\lib\utils.py", line 107, in log
                                                log_level = int(get_setting('logLevel'))
                                              File "C:\Programs\Kodi 19\portable_data\addons\service.upnext\resources\lib\utils.py", line 44, in get_setting
                                                value = to_unicode(Addon().getSetting(key))
                                            RuntimeError: Unknown addon id 'service.upnext'.
                                            -->End of Python script error report<--
2019-11-28 20:53:39.623 T:5868   DEBUG: CPythonInvoker(6, C:\Programs\Kodi 19\portable_data\addons\service.upnext\service.py): script termination took 1ms
```

**Comment by dagwieers** [comment]
Good catch, disabling the add-on from Kodi means we are no longer able to instantiate an Addon object, which we do for logging. The reason why we do this now on-the-fly is because otherwise we may not get recently changed settings. It is probably easiest to catch this and continue.

**Comment by dagwieers** [comment]
@notoco @anxdpanic @mediaminister I would like to know what others think of this.
Of the idea, the implementation and the chosen default values.

To evaluate the implementation, please only look at the second commit adf6dd08bee69937c34948cdc5d2b95604d60c7f (the first commit is PR #114)

**Comment by notoco** [comment]
I have no comments - the new settings seem clearer to me, and the new options are interesting

**Comment by notoco** [comment]
Translation done - The first one!

**Comment by dagwieers** [comment]
> The current PR still has the logic for **shortPlayMode**, **shortPlayLength** and **shortPlayNotification** included. I will remove it if it is decided that we no longer need this.

Beware that we still have to disable this functionality. I will do it in another PR.

**Pull request merged**
