### PR TITLE
Automatic stop playing and PL translation

### PR DESCRIPTION
**Pull request by notoco**
Connected to this issue:
https://github.com/im85288/service.upnext/issues/13
https://github.com/im85288/service.upnext/issues/12

### CODE REVIEW

**Comment by notoco** [comment]
Easy baby ;)
I mistakenly corrected the readme in my repository - I forgot it is a fork :)

**Comment by im85288** [comment]
Is this PR related to the issue number 11? Sorry I did not get time over the weekend. Will look as soon as possible

**Comment by notoco** [comment]
No, it has nothing to do with this mistake. I got a bit confused in these issues :) I made a fork in my github and I forgot that when applying changes in eg addon.xml appear automatically here ...

Now I removed the fork and I made a separate repository with my patch - it's easier for me to share the family quickly.

sorry for the mess ;)

**Comment by im85288** [comment]
No problem at all we all have to start somewhere. I seen issue 11 seems to be getting popular so was hoping your PR fixed it :)

**Comment by im85288** [comment]
Hi Sorry for the late comeback been very busy with real life! The auto stop playing is not something I want to add unless you make it an option in the settings. The reason being is when you cancel the dialog to play the next episode some people will complain that playback stopped (say for example it is a short episode where things are still being shown). Could you send the PR for the polish translation in a separate request or add to transfex ( I accepted your request now to collaborate there)

**Comment by notoco** [comment]
>  The reason being is when you cancel the dialog to play the next episode some people will complain that playback stopped (say for example it is a short episode where things are still being shown).

you're right. I did not think about it. can you actually do it as an option? I will send a Polish translation a week. I have absorbed some other things too

**Pull request closed without merging**
